"""Add short numbers

Revision ID: 1b08d7a2e0a7
Revises: 4192b21cd22e
Create Date: 2023-11-30 10:25:34.201139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b08d7a2e0a7'
down_revision = '4192b21cd22e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pseudo_random_id_provider', sa.Column('shorten_number', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pseudo_random_id_provider', 'shorten_number')
    # ### end Alembic commands ###
