"""Add Civicrm Study ID to study

Revision ID: eb893fd8080e
Revises: 
Create Date: 2024-06-03 13:31:22.846276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb893fd8080e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('civicrm_study_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'civicrm_study_id')
    # ### end Alembic commands ###
