from enum import Enum

class ParticipantIdentifierTypeName():
    STUDY_PARTICIPANT_ID = 'study_participant_id'
    ALLEVIATE_ID = 'alleviate_id'
    BRICCS_ID = 'briccs_id'
    CVLPRIT_ID = 'cvlprit_id'
    CVLPRIT_LOCAL_ID = 'cvlprit_local_id'
    PILOT_ID = 'pilot_id'
    DREAM_ID = 'dream_id'
    BIORESOURCE_ID = 'bioresource_id'
    GRAPHIC2_ID = 'graphic2_id'
    TMAO_ID = 'tmao_id'
    BRAVE_ID = 'brave_id'
    NHS_NUMBER = 'nhs_number'
    UHL_SYSTEM_NUMBER = 'uhl_system_number'
    UHL_HCW_COVID_19_ID = 'UHL_HCW_COVID_19_ID'
    MINERVA_ID = 'MINERVA_ID'
    MRP_HFPEF_ID = 'MRP_HFPEF_ID'
    MULTI_MORBID_PRIORITIES_ID = 'MULTI_MORBID_PRIORITIES_ID'
    NON_ADHERENCE_ID = 'NON_ADHERENCE_ID'
    NOVO5K_ID = 'NOVO5K_ID'
    PARC_ID = 'PARC_ID'
    HC_NUMBER = 'HC_NUMBER'
    CHI_NUMBER = 'CHI_NUMBER'
    PHOSP_COVID19_ID = 'PHOSP_COVID19_ID'
    PREDICT_ID = 'PREDICT_ID'
    PREECLAMPSIA_ID = 'PREECLAMPSIA_ID'
    RAPID_NSTEMI_ID = 'RAPID_NSTEMI_ID'
    RECHARGE_ID = 'RECHARGE_ID'
    REST_ID = 'REST_ID'
    SALT_ID = 'SALT_ID'
    SCAD_SURVEY_ID = 'SCAD_SURVEY_ID'
    SCAD_LOCAL_ID = 'SCAD_LOCAL_ID'
    SCAD_ID = 'SCAD_ID'
    SCAD_REG_ID = 'SCAD_REG_ID'
    SCAD_CAE_ID = 'SCAD_CAE_ID'
    SKOPE_ID = 'SKOPE_ID'
    SPACE_FOR_COPD_ID = 'SPACE_FOR_COPD_ID'
    SPIRAL_ID = 'SPIRAL_ID'
    UPFOR5_ID = 'UPFOR5_ID'
    VASCEGENS_ID = 'VASCEGENS_ID'
    YAKULT_ID = 'yakult_id'
    YOGA_ID = 'yoga_id'


    def all_types(self):
        return [getattr(self, f) for f in dir(self) if not callable(getattr(self,f)) and not f.startswith('__')]