# Edge ID in comment

class StudyName():
    ALLEVIATE = 'ALLEVIATE' # 
    AS_Progression = 'AS Progression' #
    Bioresource = 'Bioresource' # 
    BME_COVID = 'BME COVID' #
    BRAVE = 'BRAVE' # 51674
    Breathe_Deep = 'Breathe Deep' # 
    Breathlessness = 'Breathlessness' # 
    BRICCS = 'BRICCS' # 16059
    BRICCS_CT = 'BRICCS_CT' # 
    CAE = 'CAE' # 50359
    CARDIOMET = 'CARDIOMET' # 101864
    CARMER_BREATH = 'CARMER BREATH' # 
    CHABLIS = 'CHABLIS' # 129780
    CIA = 'CIA' # 
    CMR_Guide = 'CMR Guide' # 
    CMR_vs_CTFFR = 'CMR vs CT-FFR' # 	92855
    COHERE = 'COHERE' # 105410
    COPD_COVID_19 = 'COPD_COVID_19' # 132765
    COPD_INTROL = 'COPD INTROL'
    CTO = 'CTO' # 
    CVLPRIT = 'CVLPRIT' # 6439
    Dal_Gene = 'Dal-Gene' # 
    DESMOND = 'DESMOND' # 52352
    DHF = 'DHF' # 
    DISCORDANCE = 'DISCORDANCE' # 110998
    DREAM = 'DREAM' # 20305
    EASY_AS = 'EASY AS' # 90865
    EDEN = 'EDEN' # 
    EDIFY = 'EDIFY' # 
    ELASTIC_AS = 'ELASTIC-AS' # 112788
    EPIGENE1 = 'EPIGENE1' # 
    EXTEND = 'EXTEND' # 
    FAST = 'FAST' # 88249
    FOAMI = 'FOAMI' # 88510
    FORECAST_BRICCSCT_ORFAN_SCREENING = 'FORECAST BRICCSCT ORFAN SCREENING'
    GENVASC = 'GENVASC' # 13350
    Global_Views = 'Global_Views' # 
    GO_DCM = 'GO-DCM' # 107797
    GRAPHIC = 'GRAPHIC' # 34117
    GRAPHIC2 = 'GRAPHIC2' # 
    HAD = 'HAD' # 
    Heart_Failure_Screening = 'Heart Failure Screening' # 
    HIC_COVID_19 = 'HIC Covid 19' # 
    Indapamide = 'Indapamide' # 88136
    INTERFIELD = 'INTERFIELD' # 
    INTERVAL = 'INTERVAL' # 
    LENTEN = 'LENTEN' # 88905
    LIMb = 'LIMb' # 112906
    MARI = 'MARI' # 88015
    MCCANN_IMAGING = 'MCCANN_IMAGING' # 
    MEL = 'MEL' # 
    MERMAID = 'MERMAID' # 
    MI_ECMO = 'MI-ECMO' # 47133
    MINERVA = 'MINERVA' # 51707
    MRP_HFPEF = 'MRP_HFPEF' # 
    Multi_Morbid_Priorities = 'Multi Morbid Priorities' # 
    NON_ADHERENCE = 'NON_ADHERENCE' # 
    NOVO5K = 'NOVO5K' # 
    OMICS_REGISTER = 'OMICS_REGISTER' # 
    PARC = 'PARC' # 109501
    PHOSP_COVID19 = 'PHOSP_COVID19' # 134402
    Pilot = 'Pilot' # 
    PREDICT = 'PREDICT' # 97183
    Pre_Eclampsia = 'Pre-Eclampsia' # 
    RAPID_NSTEMI = 'RAPID_NSTEMI' # 89678
    RECHARGE = 'RECHARGE' # 
    REST = 'REST' # 
    SALT = 'SALT' # 122377
    SCAD = 'SCAD' # 129226
    SKOPE = 'SKOPE' # 
    SPACE_FOR_COPD = 'SPACE_FOR_COPD'
    SPIRAL = 'SPIRAL'
    TMAO = 'TMAO'
    UHL_HCW_COVID_19 = 'UHL_HCW_COVID_19' # 
    Upfor5 = 'Upfor5' # 
    VasCeGenS = 'VasCeGenS' # 
    YAKULT = 'YAKULT' # 128800
    YOGA = 'YOGA' # 107299

    def all_studies(self):
        return [getattr(self, f) for f in dir(self) if not callable(getattr(self,f)) and not f.startswith('__')]