class StudyName():
    ALLEVIATE = {'name': 'ALLEVIATE'}
    AS_Progression = {'name': 'AS Progression'}
    Bioresource = {'name': 'Bioresource'}
    BME_COVID = {'name': 'BME COVID'}
    BRAVE = {'name': 'BRAVE', 'edge_id': 51674}
    Breathe_Deep = {'name': 'Breathe Deep'}
    Breathlessness = {'name': 'Breathlessness'}
    BRICCS = {'name': 'BRICCS', 'edge_id': 16059}
    BRICCS_CT = {'name': 'BRICCS_CT'}
    CAE = {'name': 'CAE', 'edge_id': 50359}
    CARDIOMET = {'name': 'CARDIOMET', 'edge_id': 101864}
    CARMER_BREATH = {'name': 'CARMER BREATH'}
    CHABLIS = {'name': 'CHABLIS', 'edge_id': 129780}
    CIA = {'name': 'CIA'}
    CMR_Guide = {'name': 'CMR Guide'}
    CMR_vs_CTFFR = {'name': 'CMR vs CT-FFR', 'edge_id': 92855}
    COHERE = {'name': 'COHERE', 'edge_id': 105410}
    COPD_COVID_19 = {'name': 'COPD_COVID_19', 'edge_id': 132765}
    COPD_INTROL = {'name': 'COPD INTROL'}
    CTO = {'name': 'CTO'}
    CVLPRIT = {'name': 'CVLPRIT', 'edge_id': 6439}
    Dal_Gene = {'name': 'Dal-Gene'}
    DESMOND = {'name': 'DESMOND', 'edge_id': 52352}
    DHF = {'name': 'DHF'}
    DISCORDANCE = {'name': 'DISCORDANCE', 'edge_id': 110998}
    DREAM = {'name': 'DREAM', 'edge_id': 20305}
    EASY_AS = {'name': 'EASY AS', 'edge_id': 90865}
    EDEN = {'name': 'EDEN'}
    EDIFY = {'name': 'EDIFY'}
    ELASTIC_AS = {'name': 'ELASTIC-AS', 'edge_id': 112788}
    EPIGENE1 = {'name': 'EPIGENE1'}
    EXTEND = {'name': 'EXTEND'}
    FAST = {'name': 'FAST', 'edge_id': 88249}
    FOAMI = {'name': 'FOAMI', 'edge_id': 88510}
    FORECAST_BRICCSCT_ORFAN_SCREENING = {'name': 'FORECAST BRICCSCT ORFAN SCREENING'}
    GENVASC = {'name': 'GENVASC', 'edge_id': 13350}
    Global_Views = {'name': 'Global_Views'}
    GO_DCM = {'name': 'GO-DCM', 'edge_id': 107797}
    GRAPHIC = {'name': 'GRAPHIC', 'edge_id': 34117}
    GRAPHIC2 = {'name': 'GRAPHIC2'}
    HAD = {'name': 'HAD'}
    Heart_Failure_Screening = {'name': 'Heart Failure Screening'}
    HIC_COVID_19 = {'name': 'HIC Covid 19'}
    Indapamide = {'name': 'Indapamide', 'edge_id': 88136}
    INTERFIELD = {'name': 'INTERFIELD'}
    INTERVAL = {'name': 'INTERVAL'}
    LENTEN = {'name': 'LENTEN', 'edge_id': 88905}
    LIMb = {'name': 'LIMb', 'edge_id': 112906}
    MARI = {'name': 'MARI', 'edge_id': 88015}
    MCCANN_IMAGING = {'name': 'MCCANN_IMAGING'}
    MEL = {'name': 'MEL'}
    MERMAID = {'name': 'MERMAID'}
    MI_ECMO = {'name': 'MI-ECMO', 'edge_id': 47133}
    MINERVA = {'name': 'MINERVA', 'edge_id': 51707}
    MRP_HFPEF = {'name': 'MRP_HFPEF'}
    Multi_Morbid_Priorities = {'name': 'Multi Morbid Priorities'}
    NON_ADHERENCE = {'name': 'NON_ADHERENCE'}
    NOVO5K = {'name': 'NOVO5K'}
    OMICS_REGISTER = {'name': 'OMICS_REGISTER'}
    PARC = {'name': 'PARC', 'edge_id': 109501}
    PHOSP_COVID19 = {'name': 'PHOSP_COVID19', 'edge_id': 134402}
    Pilot = {'name': 'Pilot'}
    PREDICT = {'name': 'PREDICT', 'edge_id': 97183}
    Pre_Eclampsia = {'name': 'Pre-Eclampsia'}
    RAPID_NSTEMI = {'name': 'RAPID_NSTEMI', 'edge_id': 89678}
    RECHARGE = {'name': 'RECHARGE'}
    REST = {'name': 'REST'}
    SALT = {'name': 'SALT', 'edge_id': 122377}
    SCAD = {'name': 'SCAD', 'edge_id': 129226}
    SKOPE = {'name': 'SKOPE'}
    SPACE_FOR_COPD = {'name': 'SPACE_FOR_COPD'}
    SPIRAL = {'name': 'SPIRAL'}
    TMAO = {'name': 'TMAO'}
    UHL_HCW_COVID_19 = {'name': 'UHL_HCW_COVID_19'}
    Upfor5 = {'name': 'Upfor5'}
    VasCeGenS = {'name': 'VasCeGenS'}
    YAKULT = {'name': 'YAKULT', 'edge_id': 128800}
    YOGA = {'name': 'YOGA', 'edge_id': 107299}

    def all_studies(self):
        return [getattr(self, f) for f in dir(self) if not callable(getattr(self,f)) and not f.startswith('__')]