PRINTER_DEV = 'PRINTER_DEV'
PRINTER_CVRC_LAB_SAMPLE = 'PRINTER_CVRC_LAB_SAMPLE'
PRINTER_BRU_CRF_SAMPLE = 'PRINTER_BRU_CRF_SAMPLE'
PRINTER_BRU_CRF_BAG = 'PRINTER_BRU_CRF_BAG'
PRINTER_LIMB = 'PRINTER_LIMB'
PRINTER_TMF_SAMPLE = 'PRINTER_TMF_SAMPLE'
PRINTER_TMF_BAG = 'PRINTER_TMF_BAG'
PRINTER_ADDRESS = 'PRINTER_ADDRESS'

