import pytest
from identity.model import Study
from identity.printing.model import LabelPack
from identity.setup import create_base_data


@pytest.mark.parametrize(
    "study",
    [
        ('ALLEVIATE'),
        ('AS Progression'),
        ('Bioresource'),
        ('BME COVID'),
        ('BRAVE'),
        ('Breathe Deep'),
        ('Breathlessness'),
        ('BRICCS'),
        ('BRICCS_CT'),
        ('CAE'),
        ('CARDIOMET'),
        ('CARMER BREATH'),
        ('CHABLIS'),
        ('CIA'),
        ('CMR Guide'),
        ('COHERE'),
        ('COPD_COVID_19'),
        ('COPD INTROL'),
        ('CTO'),
        ('CVLPRIT'),
        ('Dal-Gene'),
        ('DESMOND'),
        ('DHF'),
        ('DISCORDANCE'),
        ('DREAM'),
        ('EASY AS'),
        ('EDEN'),
        ('EDIFY'),
        ('ELASTIC-AS'),
        ('EPIGENE1'),
        ('EXTEND'),
        ('FAST'),
        ('FOAMI'),
        ('FORECAST BRICCSCT ORFAN SCREENING'),
        ('GENVASC'),
        ('Global_Views'),
        ('GO-DCM'),
        ('GRAPHIC2'),
        ('HAD'),
        ('Heart Failure Screening'),
        ('HIC Covid 19'),
        ('Indapamide'),
        ('INTERFIELD'),
        ('INTERVAL'),
        ('LENTEN'),
        ('LIMb'),
        ('MARI'),
        ('MCCANN_IMAGING'),
        ('MEL'),
        ('MERMAID'),
        ('MI-ECMO'),
        ('MINERVA'),
        ('MRP_HFPEF'),
        ('Multi Morbid Priorities'),
        ('NON_ADHERENCE'),
        ('NOVO5K'),
        ('PARC'),
        ('PHOSP_COVID19'),
        ('Pilot'),
        ('PREDICT'),
        ('Pre-Eclampsia'),
        ('RAPID_NSTEMI'),
        ('RECHARGE'),
        ('REST'),
        ('SALT'),
        ('SCAD'),
        ('SKOPE'),
        ('SPACE_FOR_COPD'),
        ('SPIRAL'),
        ('TMAO'),
        ('UHL_HCW_COVID_19'),
        ('Upfor5'),
        ('VasCeGenS'),
        ('YAKULT'),
        ('YOGA'),
    ],
)
def test__setup__labelpacks(client, faker, study):
    create_base_data()

    assert Study.query.filter_by(name=study).one_or_none() is not None

