from identity.setup.studies import StudyName
import pytest
from identity.model import Study
from identity.printing.model import LabelPack
from identity.setup.setup import create_base_data


@pytest.mark.slow
@pytest.mark.parametrize(
    "study",
    [
        (StudyName.ALLEVIATE),
        (StudyName.AS_Progression),
        (StudyName.Bioresource),
        (StudyName.BME_COVID),
        (StudyName.BRAVE),
        (StudyName.Breathe_Deep),
        (StudyName.Breathlessness),
        (StudyName.BRICCS),
        (StudyName.BRICCS_CT),
        (StudyName.CAE),
        (StudyName.CARDIOMET),
        (StudyName.CARMER_BREATH),
        (StudyName.CHABLIS),
        (StudyName.CIA),
        (StudyName.CMR_Guide),
        (StudyName.COHERE),
        (StudyName.COPD_COVID_19),
        (StudyName.COPD_INTROL),
        (StudyName.CTO),
        (StudyName.CVLPRIT),
        (StudyName.Dal_Gene),
        (StudyName.DESMOND),
        (StudyName.DHF),
        (StudyName.DISCORDANCE),
        (StudyName.DREAM),
        (StudyName.EASY_AS),
        (StudyName.EDEN),
        (StudyName.EDIFY),
        (StudyName.ELASTIC_AS),
        (StudyName.EPIGENE1),
        (StudyName.EXTEND),
        (StudyName.FAST),
        (StudyName.FOAMI),
        (StudyName.FORECAST_BRICCSCT_ORFAN_SCREENING),
        (StudyName.GENVASC),
        (StudyName.Global_Views),
        (StudyName.GO_DCM),
        (StudyName.GRAPHIC2),
        (StudyName.HAD),
        (StudyName.Heart_Failure_Screening),
        (StudyName.HIC_COVID_19),
        (StudyName.Indapamide),
        (StudyName.INTERFIELD),
        (StudyName.INTERVAL),
        (StudyName.LENTEN),
        (StudyName.LIMb),
        (StudyName.MARI),
        (StudyName.MCCANN_IMAGING),
        (StudyName.MEL),
        (StudyName.MERMAID),
        (StudyName.MI_ECMO),
        (StudyName.MINERVA),
        (StudyName.MRP_HFPEF),
        (StudyName.Multi_Morbid_Priorities),
        (StudyName.NON_ADHERENCE),
        (StudyName.NOVO5K),
        (StudyName.PARC),
        (StudyName.PHOSP_COVID19),
        (StudyName.Pilot),
        (StudyName.PREDICT),
        (StudyName.Pre_Eclampsia),
        (StudyName.RAPID_NSTEMI),
        (StudyName.RECHARGE),
        (StudyName.REST),
        (StudyName.SALT),
        (StudyName.SCAD),
        (StudyName.SKOPE),
        (StudyName.SPACE_FOR_COPD),
        (StudyName.SPIRAL),
        (StudyName.TMAO),
        (StudyName.UHL_HCW_COVID_19),
        (StudyName.Upfor5),
        (StudyName.VasCeGenS),
        (StudyName.YAKULT),
        (StudyName.YOGA),
    ],
)
def test__setup__Studies(client, faker, study):
    create_base_data()

    assert Study.query.filter_by(name=study['name']).one_or_none() is not None

