from datetime import datetime
from identity.setup.participant_identifier_types import ParticipantIdentifierTypeName
import pytest
from identity.database import db
from identity.setup.redcap_instances import REDCapInstanceDetail
from identity.model import Study
from identity.setup.studies import StudyName
from identity.ecrfs.model import CiviCrmEcrfSource, CustomEcrfSource, ParticipantImportDefinition, RedcapInstance, RedcapProject
from identity.setup import create_base_data


CIVICRM_CRFS = [
    (
        StudyName.BRICCS,
        6,
    ),
    (
        StudyName.GENVASC,
        3,
    ),
    (
        StudyName.GRAPHIC,
        5,
    ),
    (
        StudyName.OMICS_REGISTER,
        14,
    ),
]


CUSTOM_CRFS = [
    (
        StudyName.BRICCS,
        'briccs',
    ),
]


REDCAP_CRFS = [
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.ALLEVIATE,
        98,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.ALLEVIATE,
        45,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.ALLEVIATE,
        46,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.YOGA,
        29,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.YAKULT,
        109,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.VasCeGenS,
        19,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.Upfor5,
        24,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.UHL_HCW_COVID_19,
        110,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.TMAO,
        25,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SPIRAL,
        68,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SPIRAL,
        69,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SPACE_FOR_COPD,
        102,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SPACE_FOR_COPD,
        101,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SKOPE,
        95,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CAE,
        71,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CAE,
        93,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CAE,
        97,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SCAD,
        28,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SCAD,
        77,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.SCAD,
        68,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SCAD,
        31,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.SCAD,
        12,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.SCAD,
        13,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.SALT,
        111,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.REST,
        30,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.REST,
        44,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.RAPID_NSTEMI,
        79,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Pre_Eclampsia,
        39,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.PREDICT,
        62,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.PREDICT,
        63,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.PREDICT,
        76,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Pilot,
        5,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.PHOSP_COVID19,
        44,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.PARC,
        28,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.NOVO5K,
        70,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.NON_ADHERENCE,
        87,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.Multi_Morbid_Priorities,
        38,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.MRP_HFPEF,
        99,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.MRP_HFPEF,
        100,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.MINERVA,
        53,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        38,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        39,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        40,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        41,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        42,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        43,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        44,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        45,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        46,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        47,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        50,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        51,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        52,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        61,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        62,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        64,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        65,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MINERVA,
        69,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.MI_ECMO,
        14,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.MEL,
        25,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.MCCANN_IMAGING,
        103,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.MARI,
        52,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.MARI,
        16,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        30,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        31,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        32,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        33,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        34,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        35,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        36,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        55,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        57,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.MARI,
        58,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.LIMb,
        31,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.LIMb,
        32,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.LIMb,
        34,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.LIMb,
        36,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.LENTEN,
        56,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.INTERVAL,
        55,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.INTERFIELD,
        104,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.INTERFIELD,
        105,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Indapamide,
        50,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Indapamide,
        54,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Indapamide,
        83,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Heart_Failure_Screening,
        60,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.HAD,
        23,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.GRAPHIC2,
        20,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.GO_DCM,
        91,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.GO_DCM,
        92,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.Global_Views,
        37,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.GENVASC,
        66,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.FORECAST_BRICCSCT_ORFAN_SCREENING,
        72,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.FOAMI,
        17,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.FOAMI,
        25,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.FAST,
        43,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.FAST,
        48,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.EXTEND,
        17,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.EXTEND,
        18,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.EXTEND,
        21,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.EPIGENE1,
        12,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.ELASTIC_AS,
        94,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.ELASTIC_AS,
        96,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.EDIFY,
        30,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.EDEN,
        74,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.EDEN,
        63,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.EDEN,
        66,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.EASY_AS,
        43,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.DREAM,
        8,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.DREAM,
        22,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.DREAM,
        20,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.DREAM,
        21,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.DREAM,
        24,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.DISCORDANCE,
        84,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.DISCORDANCE,
        85,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.DHF,
        70,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.DESMOND,
        19,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Dal_Gene,
        47,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CVLPRIT,
        23,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CTO,
        51,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.CTO,
        15,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.COPD_INTROL,
        41,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.COPD_COVID_19,
        108,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.COHERE,
        22,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CMR_Guide,
        59,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CIA,
        82,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CIA,
        86,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.CHABLIS,
        49,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.CARMER_BREATH,
        40,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CARDIOMET,
        67,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.CARDIOMET,
        64,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.BRICCS_CT,
        80,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.BRICCS_CT,
        81,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.BRICCS,
        24,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        13,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        14,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        15,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        16,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        17,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        18,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        19,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        25,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        26,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRICCS,
        27,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.Breathlessness,
        30,
    ),
    (
        REDCapInstanceDetail.UOL_CRF,
        StudyName.Breathe_Deep,
        43,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.BRAVE,
        26,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.BRAVE,
        29,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        28,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        37,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        54,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        56,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        59,
    ),
    (
        REDCapInstanceDetail.UHL_HSCN,
        StudyName.BRAVE,
        60,
    ),
    (
        REDCapInstanceDetail.UOL_INTERNET,
        StudyName.BME_COVID,
        40,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.Bioresource,
        9,
    ),
    (
        REDCapInstanceDetail.UHL_LIVE,
        StudyName.AS_Progression,
        37,
    ),
]


@pytest.mark.parametrize("instance, study_name, project_id", REDCAP_CRFS)
def test__create_base_data__creates_participant_import_definitions__redcap(client, faker, instance, study_name, project_id):
    ri = RedcapInstance.query.filter_by(name=instance['name']).one_or_none()
    rp = RedcapProject(
        redcap_instance_id=ri.id,
        project_id=project_id,
    )

    db.session.add(rp)
    db.session.commit()

    create_base_data()

    s = Study.query.filter_by(name=study_name).one_or_none()

    assert ParticipantImportDefinition.query.filter_by(
        study_id=s.id,
        ecrf_source_id=rp.id,
    ).one_or_none() is not None


@pytest.mark.parametrize("study_name, case_type_id", CIVICRM_CRFS)
def test__create_base_data__creates_participant_import_definitions__civicrm(client, faker, study_name, case_type_id):
    create_base_data()

    s = Study.query.filter_by(name=study_name).one_or_none()
    e = CiviCrmEcrfSource.query.filter_by(case_type_id=case_type_id).one_or_none()

    assert ParticipantImportDefinition.query.filter_by(
        study_id=s.id,
        ecrf_source_id=e.id,
    ).one_or_none() is not None


@pytest.mark.parametrize("study_name, database", CUSTOM_CRFS)
def test__create_base_data__creates_participant_import_definitions__custom(client, faker, study_name, database):
    create_base_data()

    s = Study.query.filter_by(name=study_name).one_or_none()
    e = CustomEcrfSource.query.filter_by(database_name=database).one_or_none()

    assert ParticipantImportDefinition.query.filter_by(
        study_id=s.id,
        ecrf_source_id=e.id,
    ).one_or_none() is not None


def test__create_base_data__creates_all_participant_import_definitions(client, faker):
    _create_projects()

    create_base_data()

    assert ParticipantImportDefinition.query.count() == len(REDCAP_CRFS) + len(CIVICRM_CRFS) + len(CUSTOM_CRFS)


def _create_projects():
    for instance, study_name, project_id in REDCAP_CRFS:

        ri = RedcapInstance.query.filter_by(name=instance['name']).one_or_none()

        if RedcapProject.query.filter_by(redcap_instance_id=ri.id, project_id=project_id).count() == 0:
            rp = RedcapProject(
                redcap_instance_id=ri.id,
                project_id=project_id,
            )

            db.session.add(rp)

    db.session.commit()

